### ISSUE TITLE
Create activity to display the list of pets

### ISSUE THREAD

**Issue by bobjack1313** [bobjack1313/pet_helper#28]
A rudimentary table to display a list of pets names and small photo or icon. The table cell should be fairly large. The pet's name should be fairly large to match the relative size of the icon size. Icon should be far left followed by the name. The selection of the cell should transition to the pet's information page. On the table there should be an icon or tool that will allow you to add a new pet. A tool on the far right should allow you to move the cell up or down, go to an option to delete or archive the pet.

This issue is a break out of issue #13

**Comment by SoulEmol** [comment]
0dd7d8dec1f8c4d547a37c1e5fd021ddfe7d5a01
I create a new page and change the menu. 
I added some features about the "pet list".
We can iuput the pet name, choose the date of birth...
I will add more features in this part.

**Comment by SoulEmol** [comment]
0dd7d8dec1f8c4d547a37c1e5fd021ddfe7d5a01
I have deleted the files named 'idea'
