### ISSUE TITLE
Create activity that will display the pet's general information

### ISSUE THREAD

**Issue by bobjack1313** [bobjack1313/pet_helper#29]
The activity will show a large photo of the pet with the name in large font. The activity will contain text that indicated the pet's model properties. So far: Pet Type, Pet Breed, Pet Color, Pet Age, Pet Birthday, Pet Description, Collection of pet Vets and care facilities. This page should have a control to edit the details. that will transition to a edit property page.

This issue is a breakout of Issue #9

**Comment by SoulEmol** [comment]
5d73b1a5942f643861ddbb644ebc80208e427b46
I add the new page in the home to show the information we write in the pet list, when click save it will link to the home page and then show the information,  there are still some little bugs here i will fix them and add more features.
