### ISSUE TITLE
Implement Navigation for Edit and Delete Actions

### ISSUE THREAD

**Issue by SoulEmol** [bobjack1313/pet_helper#45]
Test the edit and delete features to ensure they work as expected and handle edge cases properly.Extension of issue #14. Navigation logic will need implemented to pass along information as we transition to delete and or edit. Confirmation screen needs build in for a delte action.

**Comment by bobjack1313** [comment]
Implemented in commit fd7e5e94d5306be37cae1ddca1b20c95933f2cce
