### ISSUE TITLE
Implement the camera functionality #10.1

### ISSUE THREAD

**Issue by sahasra-123** [bobjack1313/pet_helper#53]
Create a camera functionality for the app to allow the user to take scan and upload the vet bills

Steps to follow:
- Put permissions in place so that you can access the camera.
- Make a button that will take pictures.
- Implement selection of photo from the gallery or capture the image of the bill
- Provide the access request to the user to gain the access for the user gallery.
- Make a button to choose the picture from existing gallery images or button to take a new picture.
- Provide the preview to the user before actually processing it

**Comment by bobjack1313** [comment]
This item is automatically implemented through the Android system. It will be inherently included through the functions that require usage of the camera.
