### ISSUE TITLE
Add Image picker controller

### ISSUE THREAD

**Issue by sahasra-123** [bobjack1313/pet_helper#54]
Add the controller to pick an image from the device. Attach the retrieved data to the view model. Test to ensure photo is selected and properly retrieved.

Steps to follow:

- Create a method to store the images 
- Implement a function to retrieve the images and display the which are stored previously.

**Comment by bobjack1313** [comment]
The database is setup for this functionality. The controller that drives this functionality needs to be implemented. Changing description.

**Comment by bobjack1313** [comment]
Added in commit 40e2e501999f8541cd8e78de1f11fced7223ee24
