### ISSUE TITLE
Create an UI screen for capturing  or selecting a photo

### ISSUE THREAD

**Issue by sahasra-123** [bobjack1313/pet_helper#55]
Design a screen for capturing or selecting the photo

steps to follow:

1. Create a screen and add buttons to take a picture or  choose from the gallery.
2. Display the functionalities like services, date ,amount of  from the bill.
3. Implement the navigation between screens.

**Comment by bobjack1313** [comment]
This screen will be inherently created via the image picker controller. No UI creation will be needed. This is an essential duplicate of issue #54.

**Comment by bobjack1313** [comment]
Completed with issue #54
