### ISSUE TITLE
Create the user an UI TO archive the pet profile``

### ISSUE THREAD

**Issue by sahasra-123** [bobjack1313/pet_helper#61]
Design the screen to archive the pet profile

steps to follow:

1. Add archive and unarchive buttons
2. Add confirmation functionalities to archive the pet profile
3. create a separate archived pet screen page and display the pet profiles that are archived
4.Allow users to unarchive it to the active list

**Comment by bobjack1313** [comment]
If anything, the archive should just be a button that is on the pet details screen. Probably next to a delete button. The retrieval button should allow a list to populate of archived pets. We may need to add a property to the database for Pet for a boolean toggle for archiving. The true purpose of archiving is for deceased pets that are no longer active and remain in the pet list. Nobody wants to see that.

**Comment by bobjack1313** [comment]
Mouni made changes in commits:
d9789c27a5acb33db3f1bf34b0ab04e81156fea0
216b3ea1f5019c297b1baeb9ca7f0dc9a0f080d0
