### ISSUE TITLE
Implement functionalities to archive pet profile

### ISSUE THREAD

**Issue by sahasra-123** [bobjack1313/pet_helper#62]
Implement the required functionalities to archive the pet profile

steps to follow:

1. Implement the functionality to archive the pet profile if the user don't want their pet information to appear but still stored in the database
2. Implement a function to store the archived pet profile and display them on the archived pet profile page
3. Implement functionality to unarchive the pet profile if the user want to move it back to the active list

**Comment by bobjack1313** [comment]
Mouni made changes in commits:
d9789c27a5acb33db3f1bf34b0ab04e81156fea0
216b3ea1f5019c297b1baeb9ca7f0dc9a0f080d0
